### ISSUE TITLE
Broken link for HACS installation

### ISSUE THREAD

**Issue by Szewcson** [PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net#32]
Can't install via HACS - got error 404:

```
Download failed - Got status code 404 when trying to download https://github.com/PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net/releases/download/v2.0.0/antistorm.zip 

This error originated from a custom integration.

Download failed - Got status code 404 when trying to download https://github.com/PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net/releases/download/v2.0.0/antistorm.zip
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 730, in async_download_file
    raise HacsException(
custom_components.hacs.exceptions.HacsException: Got status code 404 when trying to download https://github.com/PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net/releases/download/v2.0.0/antistorm.zip
```

**Comment by PiotrMachowski** [comment]
Have you tried restarting HA? URL has been fixed yesterday, it might be cached in your HA

**Comment by Szewcson** [comment]
**### "antistorm.zip"** - this is the issue ^^

**Comment by PiotrMachowski** [comment]
Yes, I know. It has been fixed yesterday

**Comment by Szewcson** [comment]
> Have you tried restarting HA? URL has been fixed yesterday, it might be cached in your HA

Reseted it few times today. Ok,maybe it will synchronize itself tomorrow.

**Comment by PiotrMachowski** [comment]
You can try to remove `/config/.storage/hacs.repositories` file and restart HA

**Comment by Szewcson** [comment]
Still can't install. Removed that file, reseted HA, reinstalled HACS. I have HACS 1.34.

**Comment by Szewcson** [comment]
Ok, It just installed today.

**Comment by PiotrMachowski** [comment]
So v2.0.1 works correctly?

**Comment by nepozs** [comment]
YES, v2.0.1 works flawless

**Comment by PiotrMachowski** [comment]
Great 👍
